### ISSUE TITLE
Reduce batch size?

### ISSUE THREAD

**Issue by Xaccountantlol** [suno-ai/bark#204]
I am given the error below. There are multiple folders and multiple codes. Which one needs to be updated to fix this?
   
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 508.00 MiB (GPU 0; 6.00 GiB total capacity; 4.99 GiB already allocated; 0 bytes free; 5.00 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by dm-vodopyanov** [comment]
@Xaccountantlol, as a workaround, try to use smaller models as was suggested by @Acephalia [here](https://github.com/suno-ai/bark/issues/192#issuecomment-1526806610). For me, it helped to preload the models on GPU card with 4 Gb VRAM, and the out of memory error went away.

**Comment by gkucsko** [comment]
will close this for now since we have too many threads around gpu vram usage
