### ISSUE TITLE
Not using my GPU getting very slow. I'm using windows 11 and a NVIDIA RTX 4090. Why it isn't working?

### ISSUE THREAD

**Issue by venturaEffect** [suno-ai/bark#437]
I'm following other devs guide to solve this issue but it isn't solving it.

When trying to run a script, I get: `No GPU being used. Careful, inference might be very slow!`

Went to the page [https://pytorch.org/get-started/locally/](https://pytorch.org/get-started/locally/) and saw that my CUDA version 12.2 is not available on the command prompt options so changed to my version:

`
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu122
`

Run this and got "Requirement already satisfied.... " but it still doesn't work.

So, went back to run the script but still get: `No GPU being used. Careful, inference might be very slow!`. That is weird because I already have everything installed of my NVIDIA drivers and CUDA. It came all installed when I bought it. It is completely fresh.

Any suggestion?

Appreciate.

**Comment by PastaLaPate** [comment]
Verify if your torch version is compatible with your cuda version else verify if you installed torch on the same python interpreter that you execute with. You can use `torch.cuda.is_available()` to verify

**Comment by taomas** [comment]
I solved the problem using ```pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu121```
